import { Ad } from "./types"

export const MOCK_ADS: Ad[] = [
  {
    id: "1",
    title: "Premium Wireless Headphones Campaign",
    productId: "1",
    productName: "Wireless Bluetooth Headphones",
    type: "product",
    status: "active",
    budget: 5000,
    spent: 3250,
    impressions: 125000,
    clicks: 3750,
    conversions: 187,
    ctr: 3.0,
    cpc: 0.87,
    startDate: "2024-01-15",
    endDate: "2024-02-15",
    targetCountries: ["USA", "Canada", "UK"],
    targetKeywords: ["wireless headphones", "bluetooth audio", "premium sound"],
  },
  {
    id: "2",
    title: "Smart Watch Holiday Sale",
    productId: "2",
    productName: "Smart Fitness Watch",
    type: "product",
    status: "paused",
    budget: 3000,
    spent: 1850,
    impressions: 89000,
    clicks: 2670,
    conversions: 134,
    ctr: 3.0,
    cpc: 0.69,
    startDate: "2024-01-01",
    endDate: "2024-01-31",
    targetCountries: ["USA", "Germany", "France"],
    targetKeywords: ["smart watch", "fitness tracker", "health monitor"],
  },
  {
    id: "3",
    title: "Power Bank Back to School",
    productId: "3",
    productName: "Portable Power Bank",
    type: "product",
    status: "completed",
    budget: 2500,
    spent: 2500,
    impressions: 67000,
    clicks: 2010,
    conversions: 101,
    ctr: 3.0,
    cpc: 1.24,
    startDate: "2023-12-01",
    endDate: "2023-12-31",
    targetCountries: ["USA", "UK", "Australia"],
    targetKeywords: ["power bank", "portable charger", "mobile battery"],
  },
  {
    id: "4",
    title: "Gaming Accessories Promotion",
    productId: "4",
    productName: "Gaming Mouse Pad",
    type: "product",
    status: "active",
    budget: 1500,
    spent: 750,
    impressions: 45000,
    clicks: 1350,
    conversions: 68,
    ctr: 3.0,
    cpc: 0.56,
    startDate: "2024-01-20",
    endDate: "2024-02-20",
    targetCountries: ["USA", "Japan", "South Korea"],
    targetKeywords: ["gaming mouse pad", "gaming accessories", "esports gear"],
  },
]


