import type { Product } from "./types"

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "PROD-001",
    title: "Wireless Bluetooth Headphones - Premium Quality",
    sku: "WBH-2024-001",
    categoryId: "electronics",
    category: "Electronics & Electrical",
    images: [
      "/placeholder.svg?height=400&width=400&text=Bluetooth+Headphones+Front",
      "/placeholder.svg?height=400&width=400&text=Bluetooth+Headphones+Side",
      "/placeholder.svg?height=400&width=400&text=Bluetooth+Headphones+Package",
    ],
    description:
      "High-quality wireless Bluetooth headphones with noise cancellation, premium sound quality, and long battery life. Perfect for music lovers and professionals.",
    moq: 50,
    pricingTiers: [
      { minQty: 50, maxQty: 99, unitPrice: 32 },
      { minQty: 100, maxQty: 499, unitPrice: 30 },
      { minQty: 500, maxQty: 999, unitPrice: 28 },
      { minQty: 1000, unitPrice: 25 },
    ],
    sampleAvailable: true,
    samplePrice: 45,
    totalStock: 2500,
    status: "active",
    visibility: "public",
    tags: ["bluetooth", "headphones", "wireless", "premium", "noise-cancellation"],
    leadTimeDays: 15,
    createdAt: "2024-01-10T10:30:00Z",
    views: 1245,
    inquiries: 89,
    orders: 23,
  },
  {
    id: "PROD-002",
    title: "USB-C Charging Cables - Fast Charging",
    sku: "USB-C-001",
    categoryId: "electronics",
    category: "Electronics & Electrical",
    images: [
      "/placeholder.svg?height=400&width=400&text=USB-C+Cable+Black",
      "/placeholder.svg?height=400&width=400&text=USB-C+Cable+White",
      "/placeholder.svg?height=400&width=400&text=USB-C+Cable+Package",
    ],
    description:
      "High-speed USB-C charging cables with fast charging support up to 100W. Durable braided design with reinforced connectors.",
    moq: 100,
    pricingTiers: [
      { minQty: 100, maxQty: 499, unitPrice: 3.5 },
      { minQty: 500, maxQty: 999, unitPrice: 3.0 },
      { minQty: 1000, maxQty: 4999, unitPrice: 2.5 },
      { minQty: 5000, unitPrice: 2.0 },
    ],
    sampleAvailable: true,
    samplePrice: 8,
    totalStock: 11000,
    status: "active",
    visibility: "public",
    tags: ["usb-c", "charging", "cable", "fast-charging", "braided"],
    leadTimeDays: 7,
    createdAt: "2024-01-08T15:45:00Z",
    views: 2156,
    inquiries: 156,
    orders: 45,
  },
  {
    id: "PROD-003",
    title: "Cotton T-Shirts - Premium Combed Cotton",
    sku: "CT-MIX-001",
    categoryId: "textiles",
    category: "Textiles & Apparel",
    images: [
      "/placeholder.svg?height=400&width=400&text=Cotton+T-Shirt+Colors",
      "/placeholder.svg?height=400&width=400&text=Cotton+T-Shirt+White",
      "/placeholder.svg?height=400&width=400&text=Cotton+T-Shirt+Black",
    ],
    description:
      "Premium quality cotton t-shirts made from 100% combed cotton. Soft, comfortable, and durable with excellent color retention.",
    moq: 200,
    pricingTiers: [
      { minQty: 200, maxQty: 499, unitPrice: 9.5 },
      { minQty: 500, maxQty: 999, unitPrice: 8.5 },
      { minQty: 1000, maxQty: 2999, unitPrice: 7.5 },
      { minQty: 3000, unitPrice: 6.5 },
    ],
    sampleAvailable: true,
    samplePrice: 15,
    totalStock: 2600,
    status: "active",
    visibility: "public",
    tags: ["cotton", "t-shirt", "apparel", "comfortable", "premium"],
    leadTimeDays: 25,
    createdAt: "2024-01-05T11:20:00Z",
    views: 1876,
    inquiries: 134,
    orders: 31,
  },
  {
    id: "PROD-004",
    title: "Bluetooth Portable Speakers - Waterproof",
    sku: "BT-SPK-001",
    categoryId: "electronics",
    category: "Electronics & Electrical",
    images: [
      "/placeholder.svg?height=400&width=400&text=Bluetooth+Speaker+Black",
      "/placeholder.svg?height=400&width=400&text=Bluetooth+Speaker+Blue",
      "/placeholder.svg?height=400&width=400&text=Bluetooth+Speaker+Features",
    ],
    description:
      "Compact waterproof Bluetooth speakers with powerful sound, long battery life, and rugged design perfect for outdoor activities.",
    moq: 50,
    pricingTiers: [
      { minQty: 50, maxQty: 99, unitPrice: 28 },
      { minQty: 100, maxQty: 299, unitPrice: 25 },
      { minQty: 300, maxQty: 599, unitPrice: 22 },
      { minQty: 600, unitPrice: 20 },
    ],
    sampleAvailable: true,
    samplePrice: 35,
    totalStock: 1050,
    status: "active",
    visibility: "public",
    tags: ["bluetooth", "speaker", "waterproof", "portable", "outdoor"],
    leadTimeDays: 20,
    createdAt: "2024-01-12T09:15:00Z",
    views: 987,
    inquiries: 67,
    orders: 18,
  },
  {
    id: "PROD-005",
    title: "Stainless Steel Kitchen Utensils Set",
    sku: "SS-KIT-001",
    categoryId: "home-kitchen",
    category: "Home & Kitchen",
    images: [
      "/placeholder.svg?height=400&width=400&text=Kitchen+Utensils+Set",
      "/placeholder.svg?height=400&width=400&text=Kitchen+Utensils+Detail",
      "/placeholder.svg?height=400&width=400&text=Kitchen+Utensils+Package",
    ],
    description:
      "Professional-grade stainless steel kitchen utensils set with ergonomic handles. Dishwasher safe and built to last.",
    moq: 100,
    pricingTiers: [
      { minQty: 100, maxQty: 199, unitPrice: 45 },
      { minQty: 200, maxQty: 499, unitPrice: 40 },
      { minQty: 500, maxQty: 999, unitPrice: 35 },
      { minQty: 1000, unitPrice: 30 },
    ],
    sampleAvailable: true,
    samplePrice: 55,
    totalStock: 450,
    status: "active",
    visibility: "public",
    tags: ["kitchen", "utensils", "stainless-steel", "professional", "gift-set"],
    leadTimeDays: 30,
    createdAt: "2024-01-15T14:30:00Z",
    views: 654,
    inquiries: 45,
    orders: 12,
  },
  {
    id: "PROD-006",
    title: "Solar Panel Mounting Brackets - Heavy Duty",
    sku: "SPM-BRK-001",
    categoryId: "renewable-energy",
    category: "Renewable Energy",
    images: [
      "/placeholder.svg?height=400&width=400&text=Solar+Mounting+Brackets",
      "/placeholder.svg?height=400&width=400&text=Solar+Mounting+Installation",
      "/placeholder.svg?height=400&width=400&text=Solar+Mounting+Components",
    ],
    description:
      "Heavy-duty aluminum mounting brackets for solar panels. Weather-resistant and designed for long-term outdoor use.",
    moq: 50,
    pricingTiers: [
      { minQty: 50, maxQty: 99, unitPrice: 125 },
      { minQty: 100, maxQty: 199, unitPrice: 120 },
      { minQty: 200, maxQty: 499, unitPrice: 115 },
      { minQty: 500, unitPrice: 110 },
    ],
    sampleAvailable: true,
    samplePrice: 150,
    totalStock: 180,
    status: "draft",
    visibility: "private",
    tags: ["solar", "mounting", "brackets", "renewable-energy", "aluminum"],
    leadTimeDays: 45,
    createdAt: "2024-01-20T16:00:00Z",
    views: 234,
    inquiries: 18,
    orders: 3,
  },
]


