"use client"

import type { Contact } from "./types"

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "contact-001",
    name: "Ahmed Hassan",
    company: "BuildTech Construction Ltd",
    email: "ahmed.hassan@buildtech.com",
    phone: "+971-50-123-4567",
    country: "United Arab Emirates",
    status: "active",
    lastContact: "2024-11-20T10:30:00Z",
    totalOrders: 15,
    totalRevenue: 125000,
    tags: ["construction", "steel", "high-volume"],
    notes:
      "Key client for steel pipes and construction materials. Prefers bulk orders with 30-day payment terms.",
  },
  {
    id: "contact-002",
    name: "Sarah Johnson",
    company: "EcoFashion International",
    email: "sarah@ecofashion.com",
    phone: "+1-555-0123",
    country: "United States",
    status: "active",
    lastContact: "2024-11-18T14:15:00Z",
    totalOrders: 8,
    totalRevenue: 68000,
    tags: ["textiles", "organic", "sustainable"],
    notes: "Focuses on sustainable and organic textiles. Regular orders for organic cotton products.",
  },
  {
    id: "contact-003",
    name: "Liu Wei",
    company: "MegaFactory Solutions",
    email: "liu.wei@megafactory.cn",
    phone: "+86-138-0013-8000",
    country: "China",
    status: "prospect",
    lastContact: "2024-11-15T09:45:00Z",
    totalOrders: 0,
    totalRevenue: 0,
    tags: ["electronics", "led", "industrial"],
    notes:
      "Interested in LED lighting systems for industrial applications. Potential for large volume orders.",
  },
  {
    id: "contact-004",
    name: "Maria Rodriguez",
    company: "TechnoElectronics Corp",
    email: "maria.rodriguez@technoelectronics.com",
    phone: "+34-91-123-4567",
    country: "Spain",
    status: "active",
    lastContact: "2024-11-19T16:20:00Z",
    totalOrders: 12,
    totalRevenue: 89500,
    tags: ["electronics", "components", "automotive"],
    notes: "Regular buyer of electronic components. Interested in automotive parts expansion.",
  },
  {
    id: "contact-005",
    name: "James Wilson",
    company: "Global Machinery Inc",
    email: "james.wilson@globalmachinery.com",
    phone: "+44-20-7946-0958",
    country: "United Kingdom",
    status: "active",
    lastContact: "2024-11-17T11:30:00Z",
    totalOrders: 6,
    totalRevenue: 156000,
    tags: ["machinery", "equipment", "industrial"],
    notes: "Specializes in industrial machinery. High-value orders with extended payment terms.",
  },
  {
    id: "contact-006",
    name: "Priya Sharma",
    company: "Indian Textiles Hub",
    email: "priya.sharma@indiantextiles.in",
    phone: "+91-98765-43210",
    country: "India",
    status: "prospect",
    lastContact: "2024-11-12T13:45:00Z",
    totalOrders: 2,
    totalRevenue: 15000,
    tags: ["textiles", "cotton", "wholesale"],
    notes: "New contact interested in cotton textiles. Potential for regular wholesale orders.",
  },
  {
    id: "contact-007",
    name: "Hans Mueller",
    company: "German Engineering Solutions",
    email: "hans.mueller@germaneng.de",
    phone: "+49-30-12345678",
    country: "Germany",
    status: "active",
    lastContact: "2024-11-21T08:15:00Z",
    totalOrders: 9,
    totalRevenue: 198000,
    tags: ["engineering", "precision", "automotive"],
    notes: "Requires high-precision components for automotive industry. Quality-focused buyer.",
  },
  {
    id: "contact-008",
    name: "Fatima Al-Zahra",
    company: "Gulf Trading Company",
    email: "fatima@gulftrading.ae",
    phone: "+971-4-567-8901",
    country: "United Arab Emirates",
    status: "inactive",
    lastContact: "2024-10-05T12:00:00Z",
    totalOrders: 4,
    totalRevenue: 32000,
    tags: ["trading", "general", "middle-east"],
    notes: "Previously active trader. Last contact over a month ago. May need follow-up.",
  },
  {
    id: "contact-009",
    name: "Roberto Silva",
    company: "Brazilian Imports Ltd",
    email: "roberto.silva@brazilimports.com.br",
    phone: "+55-11-9876-5432",
    country: "Brazil",
    status: "prospect",
    lastContact: "2024-11-14T15:30:00Z",
    totalOrders: 1,
    totalRevenue: 8500,
    tags: ["imports", "south-america", "machinery"],
    notes: "New prospect from South America. Interested in machinery and equipment imports.",
  },
  {
    id: "contact-010",
    name: "Yuki Tanaka",
    company: "Tokyo Electronics Co",
    email: "yuki.tanaka@tokyoelectronics.jp",
    phone: "+81-3-1234-5678",
    country: "Japan",
    status: "active",
    lastContact: "2024-11-16T10:45:00Z",
    totalOrders: 11,
    totalRevenue: 145000,
    tags: ["electronics", "precision", "technology"],
    notes:
      "High-tech electronics buyer. Focuses on precision components and latest technology.",
  },
]


